version: '3.8'
services:
  springapp:
    image: orenol/youngman_project:myspring
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/Youngman

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    volumes:
      - mongodb_data:/data/db

  reactapp:
    image: orenol/youngman_project:myreact
    ports:
      - "3000:80"

  flaskapp:
    image: orenol/youngman_project:myflask
    ports:
      - "6000:6000"
      
volumes:
  mongodb_data:
